name: open_next
description: Open Next - Linux desktop application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0  # Downgraded from ^3.0.0
  provider: ^6.0.5
  intl: ^0.18.1
  xdg_directories: ^1.0.0
  path_provider_linux: ^2.2.1
  path: ^1.8.3
  file: ^7.0.0
  shared_preferences: ^2.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.12
  geocoding: ^2.1.0
  http: ^1.1.0  # For city search API
  flutter_typeahead: ^4.6.2
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.gif
